### ISSUE TITLE
Gitter for the Publicode community

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1155]
We want to encourage people to use the Publicode language in their applications. The language is very young and using it will raise a lot of questions, you might also find bugs or undocumented behaviors.

So far we have suggested using GitHub issues on this repository to discuss these matters, but we haven't seen a lot of issues opened. We also had a shared Slack channel with the [Blank](https://blank.app/) team, which was closed because the betagouv organization is no longer a paying customer of Slack. Interestingly there was a lot more activity in this channel that there is on Github, which indicate that we miss a lot of casual questions or remarks that can lead to interesting discussions.

The barrier to entry to open an issue on Github is probably too high, so I propose that we instantiate a shared chat room with the Publicode core team and community members. [Gitter](https://gitter.im/) seems like a good choice, but maybe you have some other preference ?

Pinging some known Publicode users : @Hotsnown, @eyaconsulting, @revolunet, @simon-prst, @alexnl022, @ChrishanZ, @zaofande, @BeeDi, @glm-mrt, @lionelB

Note: @laem, you are the owner of https://github.com/publicodes so only you can create https://gitter.im/publicodes

**Comment by laem** [comment]
I've just discovered that github is lauching a discussion tool, you can try it at https://github.com/tmrowco/electricitymap-contrib/discussions
It's more a stackoverflow than a slack. What do you think would be the best tool ? Still gitter ? Both :) ?

**Comment by Hotsnown** [comment]
Hi all 👋

First of all, thanks for your awesome tool. :)

I've been using it in order to generate explanations in the inheritance law
domain <https://github.com/Hotsnown/succession>.
This is still a work in progress but I can not stress out the amount of
work you saved me from.

I did have some unexpected behaviors from the rendering of the *"variations"
*mechanism <https://publi.codes/m%C3%A9canismes#variations> so I would be
grateful to have a place to discuss it with you. *I do not have a
personal preference.*
Besides that, I'm genuinely interested to see where the project is going.

Best regards,
Pierre

**Comment by lionelB** [comment]
Hi, 
> The barrier to entry to open an issue on Github is probably too high

From my point of view, the main concern about github is that it needs a GH account as a pre-requisite and it also a pre-requisite to Gitter. So I'm curious about the barriers you identify that lead people to not discuss a problem in issues.

I would privilege an async communication channel. It would be better for user (less frustation if no one reply) and for core-team (not have to stop in their work to answer a question)

So I'm curious to try the GH discussion tools since

**Comment by mquandalle** [comment]
> the main concern about github is that it needs a GH account as a pre-requisite and it also a pre-requisite to Gitter

I've just looked at it and there are multiple auth methods
![image](https://user-images.githubusercontent.com/1730702/95744954-8ae6b280-0c94-11eb-8b8a-ebf49cee6d3f.png)

Also Gitter has a plan to switch to the Matrix protocol, which might allow more auth method (email) and compatible clients https://matrix.org/blog/2020/09/30/welcoming-gitter-to-matrix

**Comment by johangirod** [comment]
>  So I'm curious about the barriers you identify that lead people to not discuss a problem in issues.

My guess is that openning issues is quite regulated in most of the open source project, only allowing reports of clearly identified bugs or proposing a new feature. They are usually not the place to ask for help (contrary to stackoverflow). Thus, they lacks the casualness of dropping a simple question in a chat room.

>  It's more a stackoverflow than a slack. What do you think would be the best tool ? Still gitter ? Both :) ?

I think they respond to different use cases. But for praticality reasons, I would suggest to start with gitter. Indeed, since the publicode source is still kept in the mon-entreprise repo, it feels quite off to open the dedicated channel of discussion here. I would much rather wait for publicode to be migrated to its own repository before opening discussion there. 

In the mean time, we could use the official publicode gitter (with a link in the README of mon-entreprise), as well as emails for those who prefer async communication (open a mail contact@publi.codes ?)

**Comment by laem** [comment]
I've just started to transfer the domain do gandi, which will give us access to an email adress :)

**Comment by mquandalle** [comment]
Yes I think we could move the codebase in a dedicated repository soon, we just need to configure some tools to handle it like a monorepo on our side.

**Comment by mquandalle** [comment]
Let's try https://gitter.im/publicodes/community
